INSERT INTO teams (team_id, name, abbreviation, primary_color, secondary_color, logo_svg_url, league_name, division_name)
VALUES
(108,'Los Angeles Angels','LAA','#BA0021','#003263','https://www.mlbstatic.com/team-logos/team-cap-on-dark/108.svg','AL','West'),
(109,'Arizona Diamondbacks','AZ','#A71930','#E3D4AD','https://www.mlbstatic.com/team-logos/team-cap-on-dark/109.svg','NL','West'),
(110,'Baltimore Orioles','BAL','#DF4601','#000000','https://www.mlbstatic.com/team-logos/team-cap-on-dark/110.svg','AL','East'),
(111,'Boston Red Sox','BOS','#BD3039','#0C2340','https://www.mlbstatic.com/team-logos/team-cap-on-dark/111.svg','AL','East'),
(112,'Chicago Cubs','CHC','#0E3386','#CC3433','https://www.mlbstatic.com/team-logos/team-cap-on-dark/112.svg','NL','Central'),
(113,'Cincinnati Reds','CIN','#C6011F','#000000','https://www.mlbstatic.com/team-logos/team-cap-on-dark/113.svg','NL','Central'),
(114,'Cleveland Guardians','CLE','#0C2340','#E31937','https://www.mlbstatic.com/team-logos/team-cap-on-dark/114.svg','AL','Central'),
(115,'Colorado Rockies','COL','#33006F','#C4CED4','https://www.mlbstatic.com/team-logos/team-cap-on-dark/115.svg','NL','West'),
(116,'Detroit Tigers','DET','#0C2340','#FA4616','https://www.mlbstatic.com/team-logos/team-cap-on-dark/116.svg','AL','Central'),
(117,'Houston Astros','HOU','#002D62','#EB6E1F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/117.svg','AL','West'),
(118,'Kansas City Royals','KC','#004687','#BD9B60','https://www.mlbstatic.com/team-logos/team-cap-on-dark/118.svg','AL','Central'),
(119,'Los Angeles Dodgers','LAD','#005A9C','#FFFFFF','https://www.mlbstatic.com/team-logos/team-cap-on-dark/119.svg','NL','West'),
(120,'Washington Nationals','WSH','#AB0003','#14225A','https://www.mlbstatic.com/team-logos/team-cap-on-dark/120.svg','NL','East'),
(121,'New York Mets','NYM','#002D72','#FF5910','https://www.mlbstatic.com/team-logos/team-cap-on-dark/121.svg','NL','East'),
(133,'Oakland Athletics','ATH','#003831','#EFB21E','https://www.mlbstatic.com/team-logos/team-cap-on-dark/133.svg','AL','West'),
(134,'Pittsburgh Pirates','PIT','#FDB827','#27251F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/134.svg','NL','Central'),
(135,'San Diego Padres','SD','#2F241D','#FFC425','https://www.mlbstatic.com/team-logos/team-cap-on-dark/135.svg','NL','West'),
(136,'Seattle Mariners','SEA','#0C2C56','#005C5C','https://www.mlbstatic.com/team-logos/team-cap-on-dark/136.svg','AL','West'),
(137,'San Francisco Giants','SF','#FD5A1E','#27251F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/137.svg','NL','West'),
(138,'St. Louis Cardinals','STL','#C41E3A','#0C2340','https://www.mlbstatic.com/team-logos/team-cap-on-dark/138.svg','NL','Central'),
(139,'Tampa Bay Rays','TB','#092C5C','#8FBCE6','https://www.mlbstatic.com/team-logos/team-cap-on-dark/139.svg','AL','East'),
(140,'Texas Rangers','TEX','#003278','#C0111F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/140.svg','AL','West'),
(141,'Toronto Blue Jays','TOR','#134A8E','#1D2D5C','https://www.mlbstatic.com/team-logos/team-cap-on-dark/141.svg','AL','East'),
(142,'Minnesota Twins','MIN','#002B5C','#D31145','https://www.mlbstatic.com/team-logos/team-cap-on-dark/142.svg','AL','Central'),
(143,'Philadelphia Phillies','PHI','#E81828','#002D72','https://www.mlbstatic.com/team-logos/team-cap-on-dark/143.svg','NL','East'),
(144,'Atlanta Braves','ATL','#CE1141','#13274F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/144.svg','NL','East'),
(145,'Chicago White Sox','CWS','#27251F','#C4CED4','https://www.mlbstatic.com/team-logos/team-cap-on-dark/145.svg','AL','Central'),
(146,'Miami Marlins','MIA','#00A3E0','#EF3340','https://www.mlbstatic.com/team-logos/team-cap-on-dark/146.svg','NL','East'),
(147,'New York Yankees','NYY','#0C2340','#C4CED4','https://www.mlbstatic.com/team-logos/team-cap-on-dark/147.svg','AL','East'),
(158,'Milwaukee Brewers','MIL','#12284B','#FFC52F','https://www.mlbstatic.com/team-logos/team-cap-on-dark/158.svg','NL','Central')
ON CONFLICT (team_id) DO UPDATE SET
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  primary_color = EXCLUDED.primary_color,
  secondary_color = EXCLUDED.secondary_color,
  logo_svg_url = EXCLUDED.logo_svg_url,
  league_name = EXCLUDED.league_name,
  division_name = EXCLUDED.division_name;
